data_system = [
                "Host Name:                " ,
                "OS Name:                  " ,
                "OS Version:               " ,
                "OS Manufacturer:          " ,
                "OS Configuration:         " ,
                "OS Build Type:            " ,
                "Caption" ,
                "ChassisBootupState" ,
                "CreationClassName" ,
                "CurrentTimeZone" ,
                "Description" ,
                "DNSHostName" ,
                "Domain" ,
                "DomainRole" ,
                "EnableDaylightSavingsTime" ,
                "FrontPanelResetStatus" ,
                "HypervisorPresent" ,
                "InfraredSupported" ,
                "KeyboardPasswordStatus" ,
                "Manufacturer" ,
                "Model" ,
                "Name" ,
                "NetworkServerModeEnabled" ,
                "NumberOfLogicalProcessors" ,
                "NumberOfProcessors" ,
                "PartOfDomain" ,
                "PauseAfterReset" ,
                "PCSystemType" ,
                "PCSystemTypeEx" ,
                "PowerOnPasswordStatus" ,
                "PowerState" ,
                "PowerSupplyState" ,
                "PrimaryOwnerName" ,
                "ResetCapability" ,
                "ResetCount" ,
                "ResetLimit" ,
                "Roles" ,
                "Status" ,
                "SystemFamily" ,
                "SystemType" ,
                "ThermalState" ,
                "TotalPhysicalMemory" ,
                "WakeUpType" ,
                "Workgroup" ,
            ]